services:
  api:
    build:
      context: .
      dockerfile: deploy/prod/Dockerfile
    volumes:
      - ./app:/app/app
    ports:
      - "8000:8000"
    env_file:
      - app/.env
    restart: unless-stopped
