[tool.poetry]
name = "developers"
version = "0.1.0"
description = ""
authors = ["zarif.bekturdiev <zarif.bekturdiev@dteam.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
